server:
  port: 8081
spring:
  application:
    name: spring-adk-demo-agent
    mcp:
      client:
        name: my-mcp-client
        version: 0.0.1
        tool-callbacks-enabled: true
        streamable:
          http:
            connections:
              my-server:
                url: https://localhost:8080/mcp